

```{r}
library(plyr)
library(tidyverse)
library(ggplot2)
library(viridis)


absolute.path <- rprojroot::find_rstudio_root_file()
#CountyBoundary <- External[[2]]
path.to.VC55 <- fs::path(absolute.path, "data-ext","VC55", ext = "rds")

CountyBoundary <- readRDS(path.to.VC55)
# Set the ESPG
#CountyBoundary <- sf::st_set_crs(CountyBoundary, 4326)
# Reproject
# Reproject as UKNG EPSG 
CountyBoundary <- sf::st_transform(CountyBoundary, 27700)


```



```{r  fig.align='center', fig.cap= 'Map of all records by tetrad.' }

# Load the data
path.to.my.data <- fs::path( absolute.path
                               ,"data-ss","data-ss", ext = "rds")

my.data.ss <- readRDS(path.to.my.data)


# Rough check for sensible Grid reference format
data.for.spatial <- my.data.ss$grid.ref

      rows.with.GR <- grepl("([A-Z]{2})(\\d{4}|\\d{6}|\\d{8}|\\d{10})$",data.for.spatial )

   rows.to.keep <- which(rows.with.GR)  

   my.data.ss <-my.data.ss[rows.to.keep,]
   
   

my.data.geo <- eco.atlas::GBNG.to.Lat.Long(my.data.ss$grid.ref)

my.dates <- eco.atlas::Clean.dates(my.data.ss$record.date)

working.data <- cbind(my.data.ss, my.dates, my.data.geo )

all.data.df.sf <- sf::st_as_sf(working.data, coords= c("Long","Lat"))

# Set EPSG 4326 WSG84 as this is the source data
all.data.df.sf <- sf::st_set_crs(all.data.df.sf, 4326)

# Reproject as UKNG EPSG 
all.data.df.sf <- sf::st_transform(all.data.df.sf, 27700)

# Now we have data as UKNG we can work out tetrads

coordinates.of.records <- sf::st_coordinates(all.data.df.sf)

coordinates.of.records.2k <- trunc(coordinates.of.records/ 2000) *2000
colnames(coordinates.of.records.2k) <- c("X.2k", "Y.2k")
all.data.df.sf <- cbind(all.data.df.sf, coordinates.of.records.2k)
# Add coordinates as eastings and northings
coords.east.north <- coordinates.of.records
colnames(coords.east.north) <- c("easting", "northing")
all.data.df.sf <- cbind(all.data.df.sf, coords.east.north)

# Crop data

working.data <- sf::st_crop(all.data.df.sf, CountyBoundary)


#working.data <- all.data.df.sf
gplot1 <- ggplot()  + 
 geom_sf(data =CountyBoundary ) +
  geom_bin2d( data = working.data, 
              binwidth = c(2000,2000), 
              aes(x=easting, y=northing)) + 
              coord_sf(crs = 27700) +  
              scale_fill_viridis(trans = "log10")

gplot1

```


```{r  include=TRUE, fig.align='center', fig.cap= 'Phenology of all records.'}

# Create factor of included years
YYYY.factor <- working.data$YYYY %>% unique() %>% as.character() %>% fct_inseq()
MM.factor <- c("01","02","03","04","05","06","07","08","09","10","11","12")

working.data$count <- 1
temp.data.ag.by.month = aggregate(count ~ YYYY + MM, 
                                         data=working.data, sum, na.rm=TRUE)
# Add missing factor levels

temp.data.ag.by.month$YYYY <- factor(temp.data.ag.by.month$YYYY, YYYY.factor) %>% fct_inseq()
# Addd missing factor values
temp.data.ag.by.month$MM <- factor(temp.data.ag.by.month$MM, 
  levels = MM.factor )

# temp.data.ag.by.month.all$MM <- temp.data.ag.by.month.all$MM %>% as.numeric()
# temp.data.ag.by.month.all <- temp.data.ag.by.month.all[order(temp.data.ag.by.month.all$MM),]


gplotStrip <- ggplot(data = temp.data.ag.by.month)  +
    ggtitle("Records by month") +
  geom_tile( 
                      aes(y=YYYY,x=MM, fill= count))  +
   scale_y_discrete(drop = FALSE) + 
  scale_x_discrete(drop = FALSE) + 
  scale_fill_viridis( discrete = FALSE, trans = "log10", option = "A") + 
  theme_minimal() +  coord_fixed() +
  theme(axis.text.x  = element_text(angle=45, hjust = 1),
        axis.title = element_blank())

#grid.arrange(gplot1, gplot3, nrow = 1)

#grid.arrange(gplot1, gplotpost, gplotStrip, nrow = 2)
lay <- rbind(c(1,2),
             c(3,3))

#grid.arrange(gplot1,  gplotStrip, layout_matrix = lay)

gplotStrip

```

