# Create records

# Just create records

```{r}
# Set the records directory

mysubdir <- "mydirectory"

absolute.path <- rprojroot::find_rstudio_root_file()

path.to.my.data <- fs::path( absolute.path
                               ,"_records",mysubdir ) 

dir.create(path.to.my.data , recursive = TRUE, showWarnings = FALSE)

 setwd(path.to.my.data)

#setwd("~/Documents/my_github/bookdown/.....")

# Point to the custom data model
#data.model <- "../../data_model/general/data_model.Rmd"
data.model <- fs::path(absolute.path,"data_model","general", "data_model", ext = "Rmd")

datum.attributes <- list(
  "index.reference" = "index.reference",
  "record.date" = "Record Date",
  "place.name" = "Place Name",
  "grid.ref" = "Grid Reference",
  "recorder.name" = "Recorder Name",
  "record.notes" = "Record Notes",
  "method" = "Method",
  "quantity" = "Quantity",
  "determiner" = "Determiner",
  "order" = "Order" ,
  "family" = "Family",
  "sub.family" = "Sub-family",
  "genus" = "Genus",
  "taxon" = "Taxon",
  "gender" = "Gender",
  "log.number" = "Log number",
  "Bradley"= "Bradley Number",
  "common.name" = "Common Name"
)
eco.atlas::new.record( datum.attributes, data.model.path = data.model)

```

# An improved pattern for spiders

```{r}
# Set the records directory

pitfall.number <- 32

pitfall.tag <- paste("pitfall", pitfall.number, sep = "-")
pitfall.note <- paste("Pitfall", pitfall.number, sep = "-")

absolute.path <- rprojroot::find_rstudio_root_file()

path.to.my.data <- fs::path( absolute.path
                               ,"_records","pitfall", pitfall.tag )

dir.create(path.to.my.data , recursive = TRUE, showWarnings = FALSE)

 setwd(path.to.my.data)

# Point to the custom data model


data.model <- fs::path(absolute.path,"data_model","spiders", "spider_data_model", ext = "Rmd")

for(index in 1:37) {
  
  index.pad <- stringr::str_pad(index, pad = 0, 3)
  
  index.ref <- paste("PJP32",index.pad, sep = "-" )


datum.attributes <- list(
  "index.reference" = index.ref,
  "record.date" = "2021-08-19",
  "place.name" = "Rutland Water NR",
  "UKNGR" = "c(488321.4643, 306641.9398)",
  "grid.ref" = "SK8832106642",
  "status" = "1.0 Ground layer",
  "broad.habitat" = "Wetland vegetation,other",
  "recorder.name" = "P.J. Palmer, T. Sexton",
  "record.notes" = pitfall.note,
  "method" = "T1. Pitfall trap",
  "quantity" = "1",
  "determiner" = "P.J. Palmer",
  "order" = "Araneae" ,
  "family" = "Family",
  "genus" = "Genus",
  "taxon" = "Taxon",
  "gender" = "Gender",
  "stage" = "stage",
  "common.name" = ""
)
eco.atlas::new.record( datum.attributes, data.model.path = data.model)

}

```


