---
output:
  pdf_document: default
  html_document: default
---

# {{my.orders}} Records



```{r  include=TRUE, echo=FALSE,  message=FALSE, results = 'asis'}

# This code collects all the markdown records from the _records directory and
# assembles a chapter from them.
#recordID <- "202011051101PJP"

# Make sure that these library files are available
library(plyr)
library(tidyverse)
# Read all rds files
absolutePath <- getwd()
path.to.all.data <- fs::path(absolutePath,"_records")

my.record.files <- list.files(
  path.to.all.data,
  pattern = ".Rmd", # Make a suitable filter. Use the dot for a wildcard.
  full.names = TRUE,
  recursive = TRUE) 

# This drops all files that begin with an underscore.
my.record.files.rows <- grep('^_', fs::path_file(my.record.files), invert = TRUE )

my.record.files <- my.record.files[my.record.files.rows]
# Absolute path needed as a workaround to make this work with child files
# absolutePath <- getwd()
# full.path <- fs::path(absolutePath,"_records" , recordID, recordID, ext = "Rmd")
# 
# path_to_pro_forma <- full.path
my.output <- NULL
my.count.identified <- 0
my.records.to.do <- NULL
my.records.prepared <- NULL
my.records.noid <- NULL
if( length(my.record.files) > 0) { # Check we have some records to include.
  # If we have records then included them
  for(my.record in my.record.files) {
    # Dummy values to cover no rds file.
    my.record.taxon <- 1
    my.record.order <- 1
    # Check to see if we have an .rds store
    my.record.rds <-  fs::path_ext_set(my.record, "rds" ) 
    my.record.rds.exists <- my.record.rds %>% fs::file_exists()
      if(my.record.rds.exists) {
       my.record.name <- fs::path_file(my.record) %>% fs::path_ext_remove() 
      my.record.data <- readRDS(my.record.rds)  
      # Which row has taxon
      my.record.taxon <- which(my.record.data$datumAttribute == "taxon")
      my.record.order <- which(my.record.data$datumAttribute == "order")
      } # We now know if the record has been identified
    
    # Save some space on checking order
    if(my.record.rds.exists) {
    is.this.my.order <- my.record.data$datumValue[my.record.order]   == "{{my.orders}}"
    }else{
    # Compile the record to update it but do not use it.
    temp.record. <- knitr::knit_child(my.record, quiet = TRUE)
      is.this.my.order <- FALSE }    
    # Save some space on checking order
    is.this.my.order <- my.record.data$datumValue[my.record.order]   == "{{my.orders}}"
  
  # Now we use an if ladder to apply actions to the record      
  if ( (my.record.data$datumValue[my.record.taxon]   == "Taxon") &
       (is.this.my.order)
       
       ){
    
    # Keep a tally of records to identify.
    # get the file name from the path
    
    my.records.to.do <- c(my.records.to.do, my.record.name )
    my.records.to.do <- sort(my.records.to.do)
    
    # Compile the record to update it but do not use it.
    temp.record. <- knitr::knit_child(my.record, quiet = TRUE)
    
  } else if (my.record.data$datumValue[my.record.taxon]   == "Prepared" &
       (is.this.my.order)){
    
    my.records.prepared <- c(my.records.prepared, my.record.name )
    my.records.prepared <- sort(my.records.prepared)
    # Compile the record to update it but do not use it.
    temp.record. <- knitr::knit_child(my.record, quiet = TRUE)    
    
  } else if (my.record.data$datumValue[my.record.taxon]   == "NoID"&
       (is.this.my.order)){
    
    my.records.noid <- c(my.records.noid, my.record.name )
    my.records.noid <- sort(my.records.noid)
    # Compile the record to update it but do not use it.
    temp.record. <- knitr::knit_child(my.record, quiet = TRUE)    

    
  } else if (my.record.data$datumValue[my.record.order]   == "{{my.orders}}")  {
    # We assume that the record has been identified.
    my.count.identified <- my.count.identified + 1
    # Compile the record and use it
    my.output <- c(my.output, knitr::knit_child(my.record, quiet = TRUE)) 
  }

  # cat('\\newpage')
  # cat(res, sep = '\n') 
  
  } # End for loop



} # End if records to include

  # cat('\\newpage')
  # cat(my.output, sep = '\n')



```



```{r eval = TRUE, include=TRUE, echo=FALSE,  message=FALSE, results = 'asis'}
# This creates a readme file in the _records repository and a Status chapter in
# the report. Building the book three times may be needed to update the figures.
absolutePath <- getwd()
path.to.all.data <- fs::path(absolutePath,"_records")
path.to.readme.template <- fs::path(path.to.all.data,"_template_readme",ext = "Rmd")

# Get the data-ss.rds for statistics. This may be out of step so need to allow
# for its absence.
path.to.data.ss <- fs::path(absolutePath,"data-ss","data-ss", ext = "rds")
if (fs::file_exists(path.to.data.ss)) {
  my.data.ss <- readRDS(path.to.data.ss)
    my.data.ss.rows.to.keep <- which(my.data.ss$order == "{{my.orders}}")
    my.data.ss.order <- my.data.ss[my.data.ss.rows.to.keep,]
    number.of.records.in.this.order <- nrow(my.data.ss.order)
} else {
  # This sort of makes sense in context.
  number.of.records.in.this.order <- "some"
}

    
    
my.template <- readr::read_file(path.to.readme.template) %>% as.character()
   # Rewriting to use whisker template
   my.lists <- list(
     my.orders = "{{my.orders}}",
     my.record.files.total = number.of.records.in.this.order,
     my.count.identified = my.count.identified,
     length.my.records.noid = length(my.records.noid),
     combine_words.my.records.noid = knitr::combine_words(my.records.noid),
     length.my.records.prepared = length(my.records.prepared),
     combine_words.my.records.prepared = knitr::combine_words(my.records.prepared),
     length.my.records.to.do = length(my.records.to.do),
     combine_words.my.records.to.do = knitr::combine_words(my.records.to.do )
     
     )

   mylists <- as.list(my.lists)
  my.rendered.output <- whisker::whisker.render(my.template, data = my.lists, strict= FALSE)
   #m Create a readme in the _records directory.
  
  
  rendered.path <- fs::path(path.to.all.data,"_README-{{my.orders}}", ext = "md")
  
  # The readme file does not need {-} tags
  rendered.readme <- gsub("\\{-\\}", "", my.rendered.output )
  
  readr::write_file(rendered.readme, rendered.path)
  
  
  # Use the same template to create status chapters

# Remove status chapter as we just keep the md readme.  
  #   rendered.path <- fs::path(absolutePath,"04-status-{{my.orders}}", ext = "Rmd")
  # readr::write_file(my.rendered.output, rendered.path)
  # 
  
```

`r paste(my.output, collapse = "\n")`