
```{r include=TRUE, echo=FALSE, message=FALSE}
library(plyr)
library(tidyverse)

```

```{r Setup, include=TRUE, echo=FALSE, warning=FALSE, message=FALSE, error=FALSE, results='asis'}
# Set code chunk options for all chunks
# These can be overridden at the chunk level, but setting global options 
# ensures consistency of chunk behaviour.
# To print a version of this document without code set echo = FALSE. 
#Include false will ignore the code chunk completely!
knitr::opts_chunk$set(include = TRUE, 
                      echo = FALSE, 
                      warning=FALSE, 
                      message=FALSE, 
                      error=FALSE,
                      fig.pos = "p",
                      results='asis')



```

```{r  eval=TRUE,include=TRUE, echo=FALSE, results = 'asis'}

# This code collects the record_data_model
# assembles a chapter from them.
# The list of files

absolutePath <- getwd()
# Read all the data model .Rmd files in the data_model directory
path.to.data.model <- fs::path(absolutePath,"data_model" )

my.template.files <- list.files(
  path.to.data.model,
  pattern = ".Rmd$", # Make a suitable filter. Use the dot for a wildcard. note the use of the $ to match the files extension.
  full.names = TRUE,
  recursive = TRUE) 

my.template.files.names <- fs::path_file(my.template.files)

# # Absolute path needed as a workaround to make this work with child files
# absolutePath <- getwd()
# full.path <- fs::path(absolutePath,"data_model" , data_model, ext = "Rmd")
# 
# path_to_data_model <- full.path

# res <- NULL

# for (my.file in my.template.files) {
#   temp.res <- knitr::knit_child(my.file, quiet = TRUE)
#   res <- paste0(res,temp.res  )
# }
# 
# 
# #cat('\\newpage')
# cat(res, sep = '\n')


```

```{r  eval=TRUE,include=TRUE, echo=FALSE, results = 'asis'}
# We need to find out which orders are covered by the data models and the make a chapter to report on each of them.

# Read all rds files
absolutePath <- getwd()
path.to.all.data <- fs::path(absolutePath,"_records")

my.record.files <- list.files(
  path.to.all.data,
  pattern = ".rds", # Make a suitable filter. Use the dot for a wildcard.
  full.names = TRUE,
  recursive = TRUE) 

# This drops all files that begin with an underscore.
my.record.files.rows <- grep('^_', fs::path_file(my.record.files), invert = TRUE )

my.record.files <- my.record.files[my.record.files.rows]

my.record.rds.data <- my.record.files  %>%
   purrr::map_df(readRDS) 

my.orders.present.rows <- my.record.rds.data[ my.record.rds.data$datumAttribute == "order",] 

my.orders.present <- my.orders.present.rows$datumValue %>% unique()

# Drop the default order 
rows.to.keep <- which(!my.orders.present == "Order")
my.orders.present <- my.orders.present[rows.to.keep]

# Now we can use this list to create templates for the records.

# First delete the files beginning with 03-
my.files.to.delete <- list.files(
  absolutePath,
  pattern = "^03-.", # Make a suitable filter. Use the dot for a wildcard.
  full.names = TRUE,
  recursive = FALSE) %>% file.remove

# Now delete the files beginning with _04-status
my.files.to.delete <- list.files(
  absolutePath,
  pattern = "^_04-status.", # Make a suitable filter. Use the dot for a wildcard.
  full.names = TRUE,
  recursive = FALSE) %>% file.remove

# Now delete the files beginning with 04-status
my.files.to.delete <- list.files(
  absolutePath,
  pattern = "^04-status.", # Make a suitable filter. Use the dot for a wildcard.
  full.names = TRUE,
  recursive = FALSE) %>% file.remove

# Now delete the files beginning with _README.
my.files.to.delete <- list.files(
  path.to.all.data,
  pattern = "^_README.", # Make a suitable filter. Use the dot for a wildcard.
  full.names = TRUE,
  recursive = FALSE) %>% file.remove

  res <- NULL

for (each.order in my.orders.present) {
  my.lists <- list(my.orders = each.order)
  
  # Path to the template file
  my.template.path <-
    fs::path(absolutePath, "_template-records", ext = "Rmd")
  
  my.template <- readr::read_file(my.template.path) %>%   as.character()
  
  my.rendered.output <-
    whisker::whisker.render(my.template, data = my.lists, strict = FALSE)
  
  # Path to the output file
  output.name <- paste("03-", each.order, "-records", sep ="")
  my.rendered.path <- fs::path(absolutePath, output.name, ext = "Rmd")
  # Save the file
  readr::write_file(my.rendered.output, my.rendered.path)
  res <- paste0(res,my.rendered.output  )
}



# 

#cat(res)


```

```{r include=TRUE, echo=FALSE, message=FALSE}
# Make sure that these library files are available
library(plyr)
library(tidyverse)
#library(downloadthis)
# Read all rds files
absolutePath <- getwd()
path.to.all.data <- fs::path(absolutePath,"_records")
# Create a path to the book versions
path.to.book.data <- fs::path(absolutePath,"dissection-report-01", "_records") 


#path.to.all.data <- fs::path("data-ss")

my.record.data <- list.files(
  path.to.all.data,
  pattern = ".rds$", # Make a suitable filter. Use the dot for a wildcard. note the use of the $ to match the files extension.
  full.names = TRUE,
  recursive = TRUE) %>%
   purrr::map_df(readRDS) %>%
   rbind()


# Now add the data_model defined fields too.
# Read all the data model .rds files in the data_model directory
path.to.data.model <- fs::path(absolutePath,"data_model" )
# Drop duplicate triples

my.data.model <- list.files(
  path.to.data.model,
  pattern = ".rds$", # Make a suitable filter. Use the dot for a wildcard. note the use of the $ to match the files extension.
  full.names = TRUE,
  recursive = TRUE) %>%
   purrr::map_df(readRDS) %>%
   rbind() %>% unique()

# As these datum triples are from the data_model directory we set datumEntity to
# EntityAttributes and drop duplicates.

my.data.model$datumEntity <- "EntityAttributes"

my.data.model <- my.data.model %>% unique()

my.data <- rbind(my.data.model,my.record.data)

# Now we make the data wide so we can easily find attributes not defined in data
# models.

my.data.wide <- tidyr::pivot_wider(
  my.data,
  id_cols = datumEntity,
  names_from = datumAttribute,
  values_from = datumValue,
  values_fn = list
) %>%  mutate_all(as.character)

definition.df.row <- which(my.data.wide$datumEntity == "EntityAttributes")
defintion.df <- my.data.wide[definition.df.row,]

missing.definitions <- names(defintion.df)[sapply(defintion.df, anyNA)]

if(length(missing.definitions) > 0) {missing <- TRUE} else {missing <- FALSE}

missing.statement <- paste(
  "The following definitions are missing from the pro_forma in use: ", 
  knitr::combine_words(missing.definitions), sep = "")

# Now to make some csv files.
csv.path <- fs::path(absolutePath,"csv-records")
fs::dir_create(csv.path)

# Also to the book version
csv.book.path <- fs::path(absolutePath, "csv-records")
fs::dir_create(csv.book.path )

my.wide.record.data <-
  tidyr::pivot_wider(
    my.record.data,
    id_cols = datumEntity,
    names_from = datumAttribute,
    values_from = datumValue,
    values_fn = list
  ) %>%  mutate_all(as.character)

# write an rds file to data-ss
data.ss.path <- fs::path(absolutePath,"data-ss")
fs::dir_create(data.ss.path )

# Finally save the rds need to use absolute path to make this robust.
data.ss.path.file <- fs::path(data.ss.path,"data-ss", ext = "rds")

saveRDS(my.wide.record.data, data.ss.path.file )


# All fields
csv.all <- fs::path(csv.path,"csv-all-fields", ext = "gz")
write_csv(my.wide.record.data, csv.all )
# Again the book version
csv.book.all <- fs::path(csv.book.path,"csv-all-fields", ext = "csv")
write_csv(my.wide.record.data, csv.book.all )

## A button for Download

#  if(knitr::is_html_output(excludes = "epub")) {
#  downloadthis::download_file(
#   path = csv.book.all,
#   output_name = "csv-all-fields",
#   button_label = "csv-all-fields",
#   button_type = "danger",
#   has_icon = TRUE,
#   icon = "fa fa-save",
#   self_contained = FALSE
# )
#  
# }


# Record fields
my.record.field.data <- my.wide.record.data
csv.record.fields <- fs::path(csv.path,"csv-record-fields", ext = "gz")
write_csv(my.record.field.data, csv.record.fields )

# Again the book version.
# csv.book.record.fields <- fs::path(csv.book.path,"csv-record-fields", ext = "gz")
# write_csv(my.record.field.data, csv.book.record.fields )

csv.book.record.fields.csv <- fs::path(csv.book.path,"csv-record-fields", ext = "csv")
write_csv(my.record.field.data, csv.book.record.fields.csv )


## A button for Download
#  if(knitr::is_html_output(excludes = "epub")) {
#   downloadthis::download_file(
#   path = csv.book.record.fields.csv,
#   output_name = "csv-record-fields",
#   button_label = "csv-record-fields",
#   button_type = "danger",
#   has_icon = TRUE,
#   icon = "fa fa-save",
#   self_contained = FALSE
# )
#   
# }


# Finally, copy Rmd files into the _records directory for use

# The list of files

my.template.files <- list.files(
  path.to.data.model,
  pattern = ".Rmd$", # Make a suitable filter. Use the dot for a wildcard. note the use of the $ to match the files extension.
  full.names = TRUE,
  recursive = TRUE) 

# Make the new path name

new.path.to.templates <- fs::path(absolutePath,"_records", "rmd-templates")

# Make the path if it does not exist
fs::dir_create(new.path.to.templates)

# As there may be multiple template files loop through them

for (my.template in my.template.files) {
  # Get the file name
  my.template.file.name <- fs::path_file(my.template)
  # Add an underscore
  my.template.file.renamed <- paste("_", my.template.file.name
                                    , sep = "")
  # Get the actual file
  my.template.file.actual <-readr::read_file(my.template)
  # Rename the files

  new.path.to.filename <- fs::path(new.path.to.templates,
                                my.template.file.renamed )
  # Now save the files in their new home
  readr::write_file(my.template.file.actual, new.path.to.filename)
  
}

# Create a dummy readme so the system will work from a clean state.
empty.read.me.path <- fs::path(path.to.all.data,"_READMEempty", ext="md")
empty.data <- " "
readr::write_file(empty.data, empty.read.me.path)

# Now combine all the _README- files

all.README.files <- list.files(
  path.to.all.data,
  pattern = "^_README.", # Make a suitable filter. Use the dot for a wildcard. note the use of the $ to match the files extension.
  full.names = TRUE,
  recursive = FALSE) 

working.README <- NULL
for (each.README in all.README.files) {
  temp.README <- readr::read_file(each.README) %>% as.character()
  working.README <- paste(working.README, temp.README, collapse = "\n")
  
}

  my.README.path <- fs::path(path.to.all.data,"README", ext = "md")
 # Save the file
  readr::write_file(working.README, my.README.path )




# `r if(missing)  {missing.statement} else {"All Entity Attributes are defined"}`.


```
